---
version: "3.9"

services:
  splunk_standalone:
    container_name: splunk_standalone
    image: splunk/splunk:8.2.2
    command: start
    environment:
      SPLUNK_HOSTNAME: splunk
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: secret123
      SPLUNK_ROLE: splunk_standalone
      SPLUNK_LICENSE_URI: /tmp/splunk.lic
    ports:
      - 8000
      - 8089
    volumes:
      - ./splunk.lic:/tmp/splunk.lic
      - ./:/opt/splunk/etc/apps/TA-jira_issue_input
