---
version: "3.9"

services:
  splunk_standalone:
    container_name: splunk_standalone
    image: splunk/splunk:8.2.2
    command: start
    environment:
      SPLUNK_HOSTNAME: splunk
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: secret123
      SPLUNK_ROLE: splunk_standalone
      SPLUNK_LICENSE_URI: /tmp/splunk.lic
      SPLUNK_APPS_URL: https://splunkbase.splunk.com/app/2962/release/4.0.0/download
    env_file:
      - splunkbase.credentials
    ports:
      - 8000
      - 8089
    volumes:
      - ./splunk.lic:/tmp/splunk.lic
      - ./TA-jira_issue_input:/opt/splunk/etc/apps/TA-jira_issue_input
