---
version: "3.9"

services:
  splmaster001:
    container_name: splmaster001
    image: splunk/splunk:9.4.0
    command: start
    environment:
      SPLUNK_HOSTNAME: splmaster001
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: secret123
      SPLUNK_ROLE: splunk_standalone
      SPLUNK_LICENSE_URI: /tmp/splunk.lic
      SPLUNK_SECRET: "3R3ZHQLPmC2p9hzw8Mp63qprZ.HsAZILrK4HJjWXEZH0oYdhbdKEqUYJXG6.0CATXwYf5ZSoKBpIOo1qLAJOngbUXppNDdCmR5QLS7aNC5y3V5jueIPYVP5iO8kUZ1plcximud2RQjXvLjCpFfMglMNEea7NtwYYiKiytNAKhOxuGrffP3kBUOwyFIrzk11XjpJi8YFC4nx84JEFwZYgamxgUsyDBptm7zfAc0riziaG8Yp1QiP.q1j1llnuHx"
    ports:
      - 8000
    volumes:
      - ./splunk.lic:/tmp/splunk.lic
      - ./splmaster001-default.yaml:/tmp/defaults/default.yml
      - ./splmaster001-post-tasks.yaml:/tmp/ansible-post-tasks.yaml
      - ./:/tmp/appmount/
