---
name: Splunk AppInspect
on: [ push ]
jobs:
  appinspect:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Remove unrelated Splunk App files
        run: rm -r .git .github .gitignore .flake8 docker-compose.yaml pyproject.toml
      - uses: splunk/appinspect-cli-action@v1
        with:
          app_path: '.'
      - uses: actions/upload-artifact@v2
        with:
          name: AppInspect results
          path: appinspect_result.json
