---
name: Splunk AppInspect
on: [ push ]
jobs:
  appinspect:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set app version
        run: |
          version=${GITHUB_REF##*/}

          if [[ "$version" == "appinspect" ]]; then
            version="0.0.1"
          fi

          echo "APP_VERSION=$version" >> $GITHUB_ENV

      - name: Update version
        run: |
          pip install crudini
          crudini --set ${{ github.event.repository.name }}/default/app.conf launcher version $APP_VERSION
          cat ${{ github.event.repository.name }}/default/app.conf
      
      - name: Package App
        run: |
          find TA-jira_issue_input -type f -exec chmod 644 '{}' \;
          find TA-jira_issue_input -type d -exec chmod 755 '{}' \;
          find TA-jira_issue_input -type f -name "*.sh" -exec chmod +x '{}' \;
          tar -cvzf ${{ github.event.repository.name }}_${{ env.APP_VERSION }}.tgz TA-jira_issue_input
      
      - uses: splunk/appinspect-cli-action@v1
        with:
          app_path: ${{ github.event.repository.name }}_$APP_VERSION.tgz
      
      - uses: actions/upload-artifact@v2
        with:
          name: AppInspect results
          path: appinspect_result.json
