---
name: Splunk AppInspect
on: [ push ]
jobs:
  appinspect:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: splunk/appinspect-cli-action@v1
        with:
          app_path: '.'
      - uses: actions/upload-artifact@v2
        with:
          name: AppInspect results
          path: appinspect_result.json
