---
name: Splunk AppInspect
on: [ push ]
jobs:
  appinspect:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Package App
        run: |
          find TA-jira_issue_input -type f -exec chmod 644 '{}' \;
          find TA-jira_issue_input -type d -exec chmod 755 '{}' \;
          find TA-jira_issue_input -type f -name "*.sh" -exec chmod +x '{}' \;
          tar -cvzf ${{ github.event.repository.name }}_0.0.1.tgz TA-jira_issue_input
      - uses: splunk/appinspect-cli-action@v1
        with:
          app_path: ${{ github.event.repository.name }}_0.0.1.tgz
      - uses: actions/upload-artifact@v2
        with:
          name: AppInspect results
          path: appinspect_result.json
