---
name: code quality checks
on: [pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Code format checks (Black)
        uses: jpetrucciani/black-check@master
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failIf: new
          args: "bin/*.py"
