---
name: code quality checks
on: [push]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Code format checks (Black)
        uses: jpetrucciani/black-check@master
        with:
          path: ${{ github.workspace }}
