---
name: code quality checks
on: [push]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Code format checks (Black)
        uses: jpetrucciani/black-check@master
        with:
          path: ${{ github.workspace }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.12
          architecture: x64
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
