---
name: code quality checks
on: [push]
jobs:
  black_check:
    runs-on: ubuntu-latest
    steps:
      - name: Code format checks
        uses: jpetrucciani/black-check@master
        with:
          path: ${{ github.workspace }}
